#!/bin/bash

#### glitch.me platform install for haskell ghc 7.10.3, cabal 1.22.6.0
#### Assumes that you have a ready .cabal file and the relevant source files!
#### File copy order:
####   1. src/Main.hs, Setup.hs, etc.
####   2. [app name].cabal
####   2. glitch-install
####   3. glitch.json

APP_DIR=/app

# Remove glitch.me JS defaults.
if [ -f $APP_DIR/package.json ]; then
    rm -rf $APP_DIR/public \
           $APP_DIR/node_modules/ \
           $APP_DIR/views \
           $APP_DIR/package.json \
           $APP_DIR/server.js
fi

# Init cabal project if not exists.
if ls *.cabal 1> /dev/null 2>&1; then
    echo "Found cabal project"
else
    echo ".cabal file not found! Make sure to add one."
    exit 1
    # To unreliable to use:
    # Compatible with cabal 1.22.6.0
    # echo -e "$PROJECT_DOMAIN\n\n9\n\n\n\n\n1\n1\n1\ny\n2" | cabal init
fi

# Set package cache to tmp folder to preserve disk space.
if [ ! -f $APP_DIR/.cabal/config ]; then
    cabal configure
    sed -i -e 's/remote-repo-cache: \/app\/.cabal\/packages/remote-repo-cache: \/tmp\/.cabal\/packages/g' $APP_DIR/.cabal/config
    cabal update
fi

cabal install
